// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime-bplanner.proto

package com.google.transit.realtime;

public final class GtfsRealtimeBplanner {
  private GtfsRealtimeBplanner() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.transit.realtime.GtfsRealtimeBplanner.deviated);
    registry.add(com.google.transit.realtime.GtfsRealtimeBplanner.wheelchairAccessible);
  }
  public static final int DEVIATED_FIELD_NUMBER = 1061;
  /**
   * <code>extend .transit_realtime.VehicleDescriptor { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.VehicleDescriptor,
      java.lang.Boolean> deviated = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int WHEELCHAIRACCESSIBLE_FIELD_NUMBER = 1062;
  /**
   * <code>extend .transit_realtime.VehicleDescriptor { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.transit.realtime.GtfsRealtime.VehicleDescriptor,
      java.lang.Integer> wheelchairAccessible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034gtfs-realtime-bplanner.proto\022\020transit_" +
      "realtime\032\023gtfs-realtime.proto:=\n\010deviate" +
      "d\022#.transit_realtime.VehicleDescriptor\030\245" +
      "\010 \001(\010:\005false:E\n\024wheelchairAccessible\022#.t" +
      "ransit_realtime.VehicleDescriptor\030\246\010 \001(\005" +
      ":\0010B\035\n\033com.google.transit.realtime"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          deviated.internalInit(descriptor.getExtensions().get(0));
          wheelchairAccessible.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.transit.realtime.GtfsRealtime.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
